# helps automate common tasks when working with Ruby; runs tests for you

require 'rake/testtask'

Rake::TestTask.new do |t|
	t.libs << "tests"
	t.test_files = FileList['tests/test*.rb']
	t.verbose = true
end
